/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.basic.services.calculator.controller;

import com.basic.services.calculator.services.CalculatorService;
import com.basic.services.calculator.Add;
import com.basic.services.calculator.AddResponse;
import com.basic.services.calculator.Divide;
import com.basic.services.calculator.DivideResponse;
import com.basic.services.calculator.Multiply;
import com.basic.services.calculator.MultiplyResponse;
import com.basic.services.calculator.Subtract;
import com.basic.services.calculator.SubtractResponse;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/calculator")
public class CalculatorController {

    @Autowired
    private CalculatorService calculatorService;

    @RequestMapping(value = "/add", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "")
    public AddResponse add(@RequestBody Add parameters) {
        return calculatorService.add(parameters);
    }

    @RequestMapping(value = "/divide", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "")
    public DivideResponse divide(@RequestParam(value = "intA", required = false) int intA, @RequestParam(value = "intB", required = false) int intB) {
        Divide parameters = new Divide();
        parameters.setIntA(intA);
        parameters.setIntB(intB);
        return calculatorService.divide(parameters);
    }

    @RequestMapping(value = "/multiply", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "")
    public MultiplyResponse multiply(@RequestParam(value = "intA", required = false) int intA, @RequestParam(value = "intB", required = false) int intB) {
        Multiply parameters = new Multiply();
        parameters.setIntA(intA);
        parameters.setIntB(intB);
        return calculatorService.multiply(parameters);
    }

    @RequestMapping(value = "/subtract", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "")
    public SubtractResponse subtract(@RequestParam(value = "intA", required = false) int intA, @RequestParam(value = "intB", required = false) int intB) {
        Subtract parameters = new Subtract();
        parameters.setIntA(intA);
        parameters.setIntB(intB);
        return calculatorService.subtract(parameters);
    }
}
